opentodo/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', 'todo.views.index'),
    (r'^logout/$', 'django.contrib.auth.views.logout_then_login'),
    (r'^accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^admin/(.*)', admin.site.root),
)

urlpatterns += patterns('todo.views',
    url(r'^tasks/$', 'list', name='tasks_list'),
    url(r'^tasks/new/$', 'add_task', name='add_task'),
    url(r'^tasks/(?P<task_id>\d+)/comments/new/$', 'add_comment', name='add_comment'),
    url(r'^tasks/delete_comment/(?P<comment_id>\d+)/$', 'del_comment', name='del_comment'),
    url(r'^tasks/(?P<task_id>\d+)/$', 'details', name='task_details'),
    url(r'^tasks/(?P<task_id>\d+)/edit/$', 'edit', name='edit_task'),
    url(r'^tasks/(?P<task_id>\d+)/delete/$', 'delete', name='delete_task'),
    url(r'^tasks/(?P<task_id>\d+)/to_accepted/$', 'task_to_accepted', name='task_to_accepted'),
    url(r'^tasks/(?P<task_id>\d+)/to_done/$', 'task_to_done', name='task_to_done'),
    url(r'^tasks/(?P<task_id>\d+)/to_checked/$', 'task_to_checked', name='task_to_checked'),
    url(r'^tasks/(?P<task_id>\d+)/to_new/$', 'task_to_new', name='task_to_new'),

    url(r'^projects/$', 'projects_list', name='projects_list'),
    url(r'^projects/new/$', 'add_project', name='add_project'),
    url(r'^projects/(?P<project_id>\d+)/$', 'project_details', name='project_details'),
    url(r'^projects/(?P<project_id>\d+)/edit/$', 'edit_project', name='edit_project'),
    url(r'^projects/(?P<project_id>\d+)/delete/$', 'delete_project', name='delete_project'),
    url(r'^projects/delete_attach/(?P<attach_id>\d+)/$', 'delete_project_attach', name='delete_project_attach'), 
    url(r'^tasks/delete_attach/(?P<attach_id>\d+)/$', 'delete_task_attach', name='delete_task_attach'),
)

opentodo/apps/todo/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User

# Для уведомлений по e-mail
from django.template.loader import get_template
from django.template import Context
from django.conf import settings
from django.core.mail import send_mail

# Тема письма при изменении статуса задачи
TASK_NOTIF_SUBJECTS = {
    1: 'Новая задача',
    2: 'Задача принята на выполнение',
    3: 'Задача выполнена',
    4: 'Результат выполнения задачи одобрен',
    5: 'Задача открыта заново'
}

# Удаляет дублирующие значения из списка
def uniqs(seq):
    return dict(zip(seq, [None,]*len(seq))).keys()

# Генерирует upload path для FileField
def make_upload_path(instance, filename):
    upload_path = "uploads"
    if isinstance(instance, ProjectAttach):
        project_id = instance.project.id
        return u"%s/%s/%s" % (upload_path, project_id, filename)

    elif isinstance(instance, TaskAttach):
        project_id = instance.task.project.id
        return u"%s/%s/tasks/%s" % (upload_path, project_id, filename)    

# Проекты (группы задач)
class Project(models.Model):
    title = models.CharField("Проект", max_length=255)
    info = models.TextField("Описание", null=True, blank=True)
    created_at = models.DateTimeField("Дата добавления", auto_now_add=True)
    author = models.ForeignKey(User, null=True, db_column='author', related_name="projects", verbose_name="Автор")
    def __unicode__(self):
        return self.title
    def _get_tasks_count(self):
        return self.related_tasks.count()
    def _get_tasks_count_active(self):
        return self.related_tasks.exclude(status=3).exclude(status=4).count()
    tasks_count = property(_get_tasks_count)
    tasks_active_count = property(_get_tasks_count_active)

# Статусы задач
class Status(models.Model):
    title = models.CharField("Статус", max_length=50)
    def __unicode__(self):
        return self.title

# Задачи
class Task(models.Model):
    project = models.ForeignKey(Project, verbose_name="Проект", related_name="related_tasks")
    status = models.ForeignKey(Status, default=1, verbose_name="Статус")
    author = models.ForeignKey(User, null=True, db_column='author', related_name="tasks", verbose_name="Автор")
    assigned_to = models.ForeignKey(User, null=True, db_column='assigned_to', related_name="assigned_tasks", verbose_name="Ответственный")
    created_at = models.DateTimeField("Дата добавления", auto_now_add=True)
    title =  models.CharField("Задача", max_length=255)
    info = models.TextField("Описание", null=True, blank=True)
    deadline = models.DateField("Срок", null=True, blank=True)
    has_deadline = models.BooleanField(default=0)
    def __unicode__(self):
        return self.title

    # Уведомления по e-mail (о добавлении задачи, изменении статуса)
    def mail_notify(self, host='', reopened=False):
        if settings.SEND_EMAILS:
            tmpl = get_template('todo/mail/task.html')
            msg_body = tmpl.render( Context({'t':self, 'host':host}) )
            addr = ''
            if reopened:
                notif_id = 5
            else:
                notif_id = self.status.id

            if ( notif_id in (1,4,5) ) and self.assigned_to.email:
                addr = self.assigned_to.email
            elif self.author.email:
                addr = self.author.email
        
            if addr:
                send_mail('[opentodo]'+TASK_NOTIF_SUBJECTS[notif_id], msg_body, settings.EMAIL_ADDRESS_FROM, [addr], fail_silently=settings.EMAIL_FAIL_SILENTLY)
        

# Комментарии к задачам
class Comment(models.Model):
    task = models.ForeignKey(Task, related_name="comments")
    author = models.ForeignKey(User)
    message = models.TextField("Комментарий")
    created_at = models.DateTimeField("Дата", auto_now_add=True)
    class Meta:
        ordering = ['created_at']

    # Уведомление по e-mail о добавлении комментария
    def mail_notify(self, host=''):
        if settings.SEND_EMAILS:
            tmpl = get_template('todo/mail/comment.html')
            msg_body = tmpl.render( Context({'t':self.task, 'c':self, 'host':host}) )
            addrs = []
            if self.task.author.email:
                addrs.append(self.task.author.email)
            if self.task.assigned_to and self.task.assigned_to.email:
                addrs.append(self.task.assigned_to.email)
            if addrs:                
                send_mail('[opentodo] Комментарий к задаче', msg_body, settings.EMAIL_ADDRESS_FROM, uniqs(addrs), fail_silently=settings.EMAIL_FAIL_SILENTLY)

# Абстрактный класс для файлов-вложений
class CommonAttach(models.Model):
    author = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)
    attached_file = models.FileField(upload_to=make_upload_path)
    class Meta:
        abstract=True

# Аттачи к проектам
class ProjectAttach(CommonAttach):
    project = models.ForeignKey(Project, related_name="files")

# Аттачи к задачам
class TaskAttach(CommonAttach):
    task = models.ForeignKey(Task, related_name="files")

    # Уведомление по e-mail о прикреплении файла к задаче
    def mail_notify(self, host=''):
        if settings.SEND_EMAILS:
            tmpl = get_template('todo/mail/file.html')
            msg_body = tmpl.render( Context({'t':self.task, 'a':self, 'host':host}) )
            addrs = []
            if self.task.author.email:
                addrs.append(self.task.author.email)
            if self.task.assigned_to and self.task.assigned_to.email:
                addrs.append(self.task.assigned_to.email)
            
            if addrs:
                send_mail('[opentodo] Файл прикреплен к задаче', msg_body, settings.EMAIL_ADDRESS_FROM, uniqs(addrs), fail_silently=settings.EMAIL_FAIL_SILENTLY)

opentodo/apps/todo/views.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.shortcuts import render_to_response
from django.http import HttpResponse, HttpResponseRedirect, Http404, HttpRequest
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, InvalidPage
from todo.models import *
from todo.forms import *

@login_required
def index(request):
    return HttpResponseRedirect(reverse('tasks_list'))

# Список задач
@login_required
def list(request, state=0):
    order = direct = ''
    project = None

    projects = Project.objects.all()
    tasks = Task.objects.all()
    
    if request.GET.get('project_id', False):
        try:
            project_id = int(request.GET['project_id'])
        except:
            raise Http404
        if project_id != 0:
            try:
                project = Project.objects.get(pk=project_id)
            except Project.DoesNotExist:
                raise Http404
        request.session['project_id'] = project_id
    if request.GET.get('folder', False):
        request.session['folder'] = request.GET['folder']
    if request.GET.get('order', False):
        request.session['order'] = request.GET['order']
    if request.GET.get('dir', False):
        request.session['dir'] = request.GET['dir']
    if request.GET.get('hide_done', False):
        request.session['hide_done'] = request.GET['hide_done']

    params = request.session

    if params.get('project_id', False):
        if params['project_id'] != '0':
            params['project_id'] = int(params['project_id'])
            try:
                project = Project.objects.get(pk=params['project_id'])
                tasks = tasks.filter(project__id = params['project_id'])
            except Project.DoesNotExist:
                request.session['project_id'] = '0'
 
    if params.get('folder', False):
        folder = params['folder']
        if not (folder == 'inbox' or folder == 'outbox' or folder == 'all'):
            folder = 'inbox'
    else:
        folder = 'inbox'

    if folder == 'inbox':
        tasks = tasks.filter(assigned_to=request.user)
    elif folder == 'outbox':
        tasks = tasks.filter(author=request.user)

    if params.get('hide_done', False) == '1':
        hide_done = True
        tasks = tasks.exclude(status__id=3).exclude(status__id=4)
    else:
        hide_done = False


    if params.get('order', False):
        order = params['order']
    else:
        order = 'created_at'
    if params.get('dir', False):
        direct = params['dir']
    else:
        direct = 'desc'

    if order == 'created_at':
        if direct == 'desc':
            tasks = tasks.order_by('-created_at')
        else:
            tasks = tasks.order_by('created_at')
    elif order == 'deadline':
        if direct == 'desc':
            tasks = tasks.order_by('has_deadline', '-deadline', '-created_at')
        else:
            tasks = tasks.order_by('-has_deadline', 'deadline', '-created_at')
    elif order == 'project':
        if direct == 'desc':
            tasks = tasks.order_by('-project__title', '-created_at')
        else:
            tasks = tasks.order_by('project__title', '-created_at')
    elif order == 'task':
        if direct == 'desc':
            tasks = tasks.order_by('-title', '-created_at')
        else:
            tasks = tasks.order_by('title', '-created_at')
    elif order == 'status':
        if direct == 'desc':
            tasks = tasks.order_by('-status__id', '-created_at')
        else:
            tasks = tasks.order_by('status__id', '-created_at')
    elif order == 'assigned_to':
        if direct == 'desc':
            tasks = tasks.order_by('-assigned_to__first_name', '-assigned_to__last_name', '-created_at')
        else:
            tasks = tasks.order_by('assigned_to__first_name', 'assigned_to__last_name', '-created_at')
    elif order == 'author':
        if direct == 'desc':
            tasks = tasks.order_by('-author__first_name', '-author__last_name', '-created_at')
        else:
            tasks = tasks.order_by('author__first_name', 'author__last_name', '-created_at')
    else:
        order = 'created_at'
        direct = 'desc'
        tasks = tasks.order_by('-created_at')

    paginator = Paginator(tasks, 100)
    page_num = int(request.GET.get('page', '1'))
    page = paginator.page(page_num)

    return render_to_response('todo/todo_list.html', {'tasks':page.object_list, 'page':page, 'paginator':paginator, 'current_page':page_num, 'projects':projects, 'project':project, 'query':params, 'folder':folder, 'order':order, 'dir':direct, 'hide_done':hide_done, 'menu_active':'tasks' }, context_instance=RequestContext(request))

# Информация о задаче + загрузка файлов
@login_required
def details(request, task_id):
    try:
        task = Task.objects.get(pk=task_id)
    except Task.DoesNotExist:
        raise Http404

    # Список файлов
    attachments = TaskAttach.objects.filter(task=task).order_by('-id')

    # Загрузка файлов
    task_attach = TaskAttach(task=task, author=request.user)
    if request.method == 'POST':
        f = TaskAttachForm(request.POST, request.FILES, instance=task_attach)
        if f.is_valid():
            attach = f.save(commit = False)
            attach.save()
            attach.mail_notify(request.get_host())

            return HttpResponseRedirect(reverse('task_details', args=(task_id,)))
    else:
        f = TaskAttachForm(instance=task_attach)

    return render_to_response('todo/task_details.html', {'task': task, 'menu_active':'tasks', 'attachments':attachments, 'f':f }, context_instance=RequestContext(request))

# Редактировать задачу
@login_required
def edit(request, task_id):
    try:
        task = Task.objects.get(pk=task_id)
    except Task.DoesNotExist:
        raise Http404

    try:
        author = task.author
    except User.DoesNotExist:
        author = None

    if not (request.user.has_perm('todo.change_task') or request.user == author):
        return HttpResponse("Недостаточно прав для выполнения действия.")

    if request.method == 'POST':
        f = TaskFormEdit(request.POST, instance = task)
        if f.is_valid():
            t = f.save(commit = False)
            if t.deadline:
                t.has_deadline = True
            else:
                t.has_deadline = False

            assigned_to_id = request.POST.get('assigned_to', '')
            if assigned_to_id:
                t.assigned_to = User.objects.get(pk=assigned_to_id)
            else:
                t.assigned_to = None
            t.save()
            return HttpResponseRedirect(reverse('task_details', args=(task_id,)))
    else:
        f = TaskFormEdit(instance = task)
    
    users = User.objects.all().order_by('first_name', 'last_name')

    return render_to_response('todo/task_edit.html', {'form': f, 'task': task, 'users': users, 'menu_active':'tasks' }, context_instance=RequestContext(request))

# Добавить задачу
@login_required
def add_task(request):
    if request.method == 'POST':
        f = TaskFormEdit(request.POST)
        if f.is_valid():
            t = f.save(commit = False)
            if t.deadline:
                t.has_deadline = True
            t.author = request.user
            t.save()

            assigned_to_id = request.POST.get('assigned_to', '')
            if assigned_to_id:
                t.assigned_to = User.objects.get(pk=assigned_to_id)
                t.save()
                t.mail_notify(request.get_host())
            
            return HttpResponseRedirect(reverse('task_details', args=(t.id,)))
    else:        
        init_data = {
            'project': request.session.get('project_id',''),
        }
        f = TaskFormEdit(initial=init_data)
    
    users = User.objects.all().order_by('first_name', 'last_name')

    return render_to_response('todo/task_edit.html', {'form': f, 'add': True, 'users': users, 'menu_active':'tasks' }, context_instance=RequestContext(request))

# Удалить задачу
@login_required
def delete(request, task_id):
    try:
        task = Task.objects.get(pk=task_id)
    except Task.DoesNotExist:
        raise Http404

    try:
        author = task.author
    except User.DoesNotExist:
        author = None

    if not (request.user.has_perm('todo.delete_task') or request.user == author):
        return HttpResponse("Недостаточно прав для выполнения действия.")

    task.delete()
    return HttpResponseRedirect(reverse('tasks_list'))

# Список проектов
@login_required
def projects_list(request, state=0):
    projects = Project.objects.all().order_by('title')

    return render_to_response('todo/projects_list.html', {'projects': projects, 'menu_active':'projects' }, context_instance=RequestContext(request))

# Информация о проекте + загрузка файлов
@login_required
def project_details(request, project_id):
    try:
        project = Project.objects.get(pk=project_id)
    except Project.DoesNotExist:
        raise Http404

    # Список файлов
    attachments = ProjectAttach.objects.filter(project=project).order_by('-id')
    
    # Загрузка файлов
    project_attach = ProjectAttach(project=project, author=request.user)
    if request.method == 'POST':
        f = ProjectAttachForm(request.POST, request.FILES, instance=project_attach)
        if f.is_valid():
            attach = f.save(commit = False)
            attach.save()
            return HttpResponseRedirect(reverse('project_details', args=(project_id,)))
    else:
        f = ProjectAttachForm(instance=project_attach)

    return render_to_response('todo/project_details.html', {'project':project, 'menu_active':'projects', 'attachments':attachments, 'f':f }, context_instance=RequestContext(request))

# Удалить файл, прикрепленный к проекту
@login_required
def delete_project_attach(request, attach_id):
    try:

opentodo/templates/todo/comment_actions.html
<a href="javascript:if(confirm('Удалить комментарий?')) location.href='{% url del_comment comment.id %}'"><img src="{{MEDIA_URL}}/img/cross_small.gif" style="vertical-align:middle" alt="" width="16" height="16" title="удалить" /></a>

opentodo/templates/todo/file_actions.html
{% load todo_extras %}

{% ifequal menu_active 'tasks' %}
<a href="javascript:if(confirm('Удалить файл {{a.attached_file.path|attach}}?')) location.href='{% url delete_task_attach a.id %}'" style="color:red;font-weight:normal"><img src="{{MEDIA_URL}}/img/cross_small.gif" alt="" width="16" height="16" title="удалить" /></a>
{% else %}{% ifequal menu_active 'projects' %}
<a href="javascript:if(confirm('Удалить файл {{a.attached_file.path|attach}}?')) location.href='{% url delete_project_attach a.id %}'" style="color:red;font-weight:normal"><img src="{{MEDIA_URL}}/img/cross_small.gif" alt="" width="16" height="16" title="удалить" /></a>
{% endifequal %}{% endifequal %}

opentodo/templates/todo/files.html
{% load todo_extras %}

<script type="text/javascript"> 
$(document).ready(function(){
	if ($("#attach_form").is(':visible')) {
		$("#add_file_link").hide();
	}
	$("#add_file_link").click(function () {
		$("#attach_form").toggle();
		if ($("#attach_form").is(':visible')) {
			$("#add_file_link").hide();
		}
	});
	$("#hide_link").click(function () {
		$("#attach_form").hide();
		$(".formErrors").hide();
		$("#add_file_link").show();
		$("#id_attached_file").removeClass('invalidInput');
	});

	$("#id_attached_file").attr("required", "true");
	
	$('#attach_form').formValidation({
		err_class: "invalidInput",
		display_alert: false
	});

});
</script>

<h1 style="display:inline">Файлы</h1>&nbsp;&nbsp;<a href="#" id="add_file_link" class="do">добавить файл</a><br /><br />

<form method="post" enctype="multipart/form-data" id="attach_form" {% if not f.errors %}style="display:none"{% endif %}>
<div class="editformWrapper" style="margin-bottom:20px; width: 600px">
<div class="formErrors">
{% if f.attached_file.errors %}Не выбран файл<br />{% endif %}
</div>
Файл: {{f.attached_file}} <input type="submit" value="Загрузить" />&nbsp;&nbsp;<a href="#" id="hide_link">отмена</a>
</div>
</form>

{% if attachments %}
<div class="attachments">

{% for a in attachments %}
<a href="{{ a.attached_file.url }}">{{a.attached_file.name|attach}}</a> ({{a.attached_file.size|kilobytes}} Кб) &#151; {{a.author|username}}, {{a.created_at|format_date}}

{% ifequal a.author user %}
	{% include "todo/file_actions.html" %}
{% else %}
	{% ifequal menu_active 'tasks' %}
		{% if perms.todo.delete_taskattach %}
			{% include "todo/file_actions.html" %}
		{% endif %}
	{% else %}{% ifequal menu_active 'projects' %}
		{% if perms.todo.delete_projectattach %}
			{% include "todo/file_actions.html" %}
		{% endif %}
	{% endifequal %}{% endifequal %}
{% endifequal %}

<br />
{% endfor %}

</div>
{% endif %}

opentodo/templates/todo/project_actions.html
<br /><a href="{% url edit_project project.id %}"><img src="{{MEDIA_URL}}/img/pencil.gif" alt="" width="16" height="16" title="редактировать" /></a>&nbsp;&nbsp;<a href="javascript:if(confirm('Удалить проект {{project.title}}?')) location.href='{% url delete_project project.id %}'" style="color: red"><img src="{{MEDIA_URL}}/img/cross.gif" alt="" width="16" height="16" title="удалить" /></a>

opentodo/templates/todo/project_delete_cannot.html
{% extends "todo.html" %}
{% load todo_extras %}

{% block title %}Нельзя удалить проект "{{project}}"{% endblock %}

{% block left %}
<a href={% url projects_list %}>&larr; Назад к проектам</a>
{% endblock %}

{% block content %}
<big>Проект <a href="{% url project_details project.id %}">{{ project.title }}</a> содержит задачи ({{project.tasks_count}}), поэтому его нельзя удалить<big>.
{% endblock %}

opentodo/templates/todo/project_details.html
{% extends "todo.html" %}
{% load todo_extras %}

{% block extra_media %}
{{f.media}}
{% include "extra_css.html" %}
{% endblock %}

{% block title %}{{project}}{% endblock %}

{% block left %}

<div>
<b>Автор</b><br />
<span>{{project.author|username}}</span>
</div>
<div class="top-indent">
<b>Дата создания</b><br />
<span>{{project.created_at|format_date:"short"}}</span>
</div>
{% ifequal project.author user %}
	{% include "todo/project_actions.html" %}
{% else %}
	{% if perms.todo.change_project %}
		{% include "todo/project_actions.html" %}
	{% endif %}
{% endifequal %}

{% endblock %}

{% block content %}
<div id="task-container" style="padding-bottom:0">
<h2 id="task-title">{{project.title}}</h2>
{% if project.info %}
<div id="task-info">{{project.info|linebreaksbr}}</div>
{% endif %}

<div id="task-action">
<a href="{% url tasks_list %}?project_id={{project.id}}&folder=all" class="bigger">Задачи</a>
<sup>({{project.tasks_count}}{%if project.tasks_active_count%}, <b>{{project.tasks_active_count}}</b>{% endif %})</sup>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="{% url projects_list %}" class="bigger">Назад к проектам &rarr;</a>
</div>

</div>

<a name="files"></a>
{% include "todo/files.html" %}

{% endblock %}

opentodo/templates/todo/project_edit.html
{% extends "todo.html" %}

{% block extra_media %}{{form.media}}{% endblock %}

{% block title %}{% if add %}Добавление проекта{% else %}Редактирование проекта "{{project}}"{% endif %}{% endblock %}

{% block content %}
<h1>{% if add %}Добавление{% else %}Редактирование{% endif %} проекта</h1>
{% include "todo/project_form.html" %}

{% endblock %}

opentodo/templates/todo/project_form.html
<script type="text/javascript"> 
$(document).ready(function(){
	$("#id_title").attr("required", "true");
	$("#id_deadline").attr("mask", "datemask");
	
	$('#editform').formValidation({
		err_class: "invalidInput",
		display_alert: false
	});
});
</script> 

<div class="formErrors">
	{% if form.title.errors %}Не введено название проекта<br />{% endif %}
</div>

<div class="editformWrapper" style="width:800px">
<form method="post" id="editform">
	<div class="fieldWrapper">
		<label for="id_title"><span class="red">*</span> Проект:</label>
		{{form.title}}
	</div>
	<div class="fieldWrapper">
		<label for="id_info">Описание:</label>
		{{form.info}}
	</div>
	<div class="fieldWrapper fieldWrapperIndent">
		<label>&nbsp;</label><input type="submit" value="Сохранить проект" class="button" /><a href="{% if add %}{% url projects_list %}{% else %}{% url project_details project.id %}{% endif %}">отмена</a>
	</div>
</form>
</div>

{% if add %}
<script language="javascript">
	document.getElementById('id_title').focus();
</script>
{% endif %}

opentodo/templates/todo/task_actions.html
<br />
<a href="{% url edit_task task.id %}"><img src="{{MEDIA_URL}}/img/pencil.gif" alt="" width="16" height="16" title="редактировать" /></a>&nbsp;&nbsp;<a href="javascript:if(confirm('Удалить задачу?')) location.href='{% url delete_task task.id %}'" style="color:red"><img src="{{MEDIA_URL}}/img/cross.gif" alt="" width="16" height="16" title="удалить" /></a>

opentodo/templates/todo/task_edit.html
{% extends "todo.html" %}

{% block extra_media %}{{form.media}}{% endblock %}

{% block title %}{% if add %}Добавление задачи{% else %}Редактирование задачи "{{task}}"{% endif %}{% endblock %}

{% block content %}
<h1>{% if add %}Добавление{% else %}Редактирование{% endif %} задачи</h1>
{% include "todo/task_form.html" %}

{% endblock %}

opentodo/templates/todo/task_form.html
{% load todo_extras %}
<script type="text/javascript"> 
$(document).ready(function(){
	$('#id_deadline').attachDatepicker({showOn:'both', buttonImage:'{{MEDIA_URL}}/img/calendar.gif', buttonImageOnly:true});

	$("#id_project").attr("required", "true");
	$("#id_title").attr("required", "true");
	$("#id_deadline").attr("mask", "datemask");
	
	$('#editform').formValidation({
		err_class: "invalidInput",
		display_alert: false,
		datemask : /[0-9]{4}-[0-9]{2}-[0-9]{2}/
	});
});
</script> 

<div class="formErrors">
	{% if form.project.errors %}Не выбран проект<br />{% endif %}
	{% if form.title.errors %}Не введена задача<br />{% endif %}
	{% if form.deadline.errors %}Формат даты в поле Срок должен быть yyyy-mm-dd<br />{% endif %}
</div>


<div class="editformWrapper" style="width:780px">
<form method="post" id="editform">
	<div class="fieldWrapper">
		<label for="id_project"><span class="red">*</span> Проект:</label>
		{{form.project}}
	</div>
	<div class="fieldWrapper">
		<label for="id_title"><span class="red">*</span> Задача:</label>
		{{form.title}}
	</div>
	<div class="fieldWrapper">
		<label for="id_info">Описание:</label>
		{{form.info}}
	</div>
	<div class="fieldWrapper">
		<label for="id_deadline">Срок:</label>
		{{form.deadline}}
	</div>
	<div class="fieldWrapper">
		<label for="id_assigned_to">Ответственный:</label>
		<select name="assigned_to" id="id_assigned_to"> 
		<option value="" selected="selected">---------</option>
	{% for u in users %}
		<option value="{{u.id}}"{% if add %}{% ifequal u.id user.id %} selected="selected"{% endifequal %}{% else %}{% ifequal u.id task.assigned_to.id %} selected="selected"{% endifequal %}{% endif %}>{{u|username}}</option> 
	{% endfor %}
		</select>
	</div>
	<div class="fieldWrapper fieldWrapperIndent">
		<label>&nbsp;</label><input type="submit" value="Сохранить задачу" class="button" /><a href="{% if add %}{% url tasks_list %}{% else %}{% url task_details task.id %}{% endif %}">отмена</a>
	</div>
</form>
</div>

{% if add %}
<script language="javascript">
if (document.getElementById('id_project').selectedIndex > 0) {
	document.getElementById('id_title').focus();
}
</script>
{% endif %}